#ifndef DESKTOP_RECORDER_GLOBAL_H_
#define DESKTOP_RECORDER_GLOBAL_H_

#include <QtCore/QtGlobal>

#if defined (DESTOPRECORDER_LIBRARY)
#  define DESKTOPRECORDERAPI Q_DECL_EXPORT
#else
#  define DESKTOPRECORDERAPI Q_DECL_IMPORT
#endif

#endif // DESKTOPRECORDER_GLOBAL_H_
